openapi: 3.0.0
servers:
  - description: "SwaggerHub API Auto Mocking"
    url: https://virtserver.swaggerhub.com/VNGRealisatie/api/kadastraal_object/v20181201
  - description: "Referentie-implementatie"
    url: https://www.voorbeeldgemeente.nl/api/kadastraal_object/v20181201
info:
  title: Kadastraal object
  description: "Dit is de toepassing Extra Services Dataverzoeken. D.m.v. deze toepassing worden meerdere, korte bevragingen op de Basis Registratie Kadaster beschikbaar gesteld. Deze toepassing betreft het verstrekken van Kadastrale Onroerende Zaak informatie."
  version: "20181201"
  contact:
    url: https://github.com/VNG-Realisatie/BRK-Bevragingen
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
paths:
  /kadastraalonroerendezaken/{kadastraleaanduiding}:
    get:
      operationId: Getskadastraalobject
      description: "Het ophalen van een Kadastraal object"
      parameters: 
        - in: query
          name: expand
          description: "Hier kan aangegeven worden welke gerelateerde resources meegeladen moeten worden. Resources en velden van resources die gewenst zijn kunnen in de expand parameter kommagescheiden worden opgegeven. Specifieke velden van resource kunnen worden opgegeven door het opgeven van de resource-naam gevolgd door de veldnaam, met daartussen een punt."
          required: false
          schema:
            type: string
        - in: path
          name: kadastraleaanduiding
          description: "De Kadaster identificatie is een door het Kadaster toegekend landelijk uniek nummer aan dit object binnen de kadastrale registratie."
          required: true
          schema:
            type: string
            maxLength: 16
        - in: query
          name: fields
          description: "Geeft de mogelijkheid de inhoud van de body van het antwoord naar behoefte aan te passen. Bevat een door komma's gescheiden lijst van veldennamen. Als niet-bestaande veldnamen worden meegegeven wordt een 400 Bad Request teruggegeven. Wanneer de parameter fields niet is opgenomen, worden alle gedefinieerde velden die een waarde hebben teruggegeven."
          required: false
          schema:
            type: string
      responses:
        '200':
          description: "Zoekactie geslaagd"
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/warning"
            X-Rate-Limit-Limit:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/X_Rate_Limit_Limit"
            X-Rate-Limit-Remaining:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/X_Rate_Limit_Remaining"
            X-Rate-Limit-Reset:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/X_Rate_Limit_Reset"
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Kadastraalonroerendezaak'
        '401':
          description: Unauthorized
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/api_version"
          content:
            application/problem+json:
              schema:
                $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/Foutbericht"
        '403':
          description: Forbidden
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/api_version"
          content:
            application/problem+json:
              schema:
                $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/Foutbericht"
        '404':
          description: Not Found
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/api_version"
          content:
            application/problem+json:
              schema:
                $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/Foutbericht"
        '406':
          description: Not Acceptable
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/api_version"
          content:
            application/problem+json:
              schema:
                $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/Foutbericht"
        '409':
          description: Conflict
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/api_version"
          content:
            application/problem+json:
              schema:
                $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/Foutbericht"
        '410':
          description: Gone
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/api_version"
          content:
            application/problem+json:
              schema:
                $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/Foutbericht"
        '415':
          description: Unsupported Media Type
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/api_version"
          content:
            application/problem+json:
              schema:
                $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/Foutbericht"
        '429':
          description: Too Many Requests
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/api_version"
          content:
            application/problem+json:
              schema:
                $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/Foutbericht"
        '500':
          description: Internal Server Error
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/api_version"
          content:
            application/problem+json:
              schema:
                $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/Foutbericht"
        'default':
          description: Er is een onverwachte fout opgetreden.
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/api_version"
          content:
            application/problem+json:
              schema:
                $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/Foutbericht"
      tags: 
      - Kadastrale objecten
components:
  schemas:
    Kadastraalonroerendezaak:
      type: "object"
      description: "URI https://tax.kadaster.nl/doc/begrip/Onroerende_zaak"
      required:
      - "identificatie"
      - "kadastraleaanduiding"
      properties:
        omschrijvingonderzoekerfdienstbaarheden:
          type: "string"
          title: "omschrijvingOnderzoekErfdienstbaarheden"
          description: ""
          pattern: \S[\s\S.]*
        toestandsdatumonderzoekerfdienstbaarheden:
          type: "string"
          title: "toestandsdatumOnderzoekErfdienstbaarheden"
          description: ""
          format: "date"
        toelichtingbewaarder:
          type: "string"
          title: "toelichtingBewaarder"
          pattern: \S[\s\S.]*
          description: ""
        identificatie:
          $ref: "#/components/schemas/CompositeID"
        kadastraleaanduiding:
          $ref: "#/components/schemas/TypeKadastraleAanduiding"
        aardcultuuronbebouwd:
          $ref: "#/components/schemas/Waardelijst_tabel"
        aardcultuurbebouwd:
          $ref: "#/components/schemas/Waardelijst_tabel"
        landinrichtingsrente:
          type: "array"
          items:
            $ref: "#/components/schemas/Landinrichtingsrente"
        koopsom:
          $ref: "#/components/schemas/Koopsom"
        _links:
          $ref: "#/components/schemas/Kadastraalonroerendezaak_links"
        _embedded:
          $ref: "#/components/schemas/Kadastraalonroerendezaak_embedded"
    Zakelijkrecht:
      type: "object"
      description: "URI https://tax.kadaster.nl/doc/begrip/Zakelijk_recht"
      required:
      - "identificatie"
      - "aard"
      properties:
        toelichtingbewaarder:
          type: "string"
          title: "toelichtingBewaarder"
          description: "ToelichtingBewaarder is een aanvullende toelichting van de\
            \ bewaarder op een geregistreerd feit. ToelichtingBewaarder is een aanvullende\
            \ toelichting van de bewaarder op een geregistreerd feit. ToelichtingBewaarder\
            \ is een aanvullende toelichting van de bewaarder op een geregistreerd\
            \ feit."
          pattern: \S[\s\S.]*
        identificatie:
          $ref: "#/components/schemas/CompositeID"
        aard:
          $ref: "#/components/schemas/Waardelijst_tabel"
        _links:
          $ref: "#/components/schemas/Zakelijkrecht_links"
    Landinrichtingsrente:
      type: "object"
      description: "De rente die berekend wordt over de percelen die in een herverkavelingblok\
        \ van een landinrichtingsproject hebben gelegen. Deze rente wordt berekend\
        \ om de niet gesubsidieerde kosten van het herverkavelingproject te dekken."
      required:
      - "eindjaar"
      properties:
        eindjaar:
          type: "string"
          title: "eindjaar"
          description: "Het laatste kalenderjaar waarin de rente in het kader van\
            \ landinrichtingswet nog verschuldigd is."
          format: "date_fullyear"
          pattern: "^[1-2]{1}[0-9]{3}$"
        bedrag:
          $ref: "#/components/schemas/Bedrag"
    Koopsom:
      type: "object"
      description: "De koopsom is het in een ter inschrijving aangeboden stuk vermelde\
        \ bedrag, waarvoor 1 of meer onroerende zaken zijn verkregen, alsmede het\
        \ koopjaar (Het jaar van overdracht waarbij deze koopsom bij deze onroerende\
        \ zaak in de akte is vermeld.) en een indicator of het meerdere onroerende\
        \ goederen betreft. Koopsom is altijd een positief bedrag. Dit is een bedrag\
        \ (omgerekend naar) euro's."
      required:
      - "indicatiemeerobjecten"
      properties:
        koopjaar:
          type: "string"
          title: "koopjaar"
          description: "Het jaar waarin het belangrijkste recht van het kadastraal\
            \ object is verkregen."
          format: "date_fullyear"
          pattern: "^[1-2]{1}[0-9]{3}$"
        indicatiemeerobjecten:
          type: "boolean"
          title: "indicatieMeerObjecten"
          description: "Geeft aan of de koopsom betrekking heeft op meer dan 1 kadastraal\
            \ object."
        bedrag:
          $ref: "#/components/schemas/Bedrag"
    CompositeID:
      type: "object"
      description: "CompositeID is een samengesteld datatype gebruikt wordt de universeel\
        \ unieke identificatie van een object binnen een registratie."
      required:
      - "namespace"
      - "lokaalid"
      properties:
        namespace:
          type: "string"
          title: "namespace"
          description: ""
          pattern: NL\.[A-Za-z]+\.[A-Za-z]+
          minLength: 1
        lokaalid:
          type: "string"
          title: "lokaalID"
          description: ""
          pattern: "[1-9][0-9]{0,14}"
          maxLength: 15
          minLength: 1
        versie:
          type: "string"
          title: "versie"
          description: ""
          pattern: "[1-9][0-9]{0,14}"
    TypeKadastraleAanduiding:
      type: "object"
      description: "Kadastrale aanduiding is de unieke aanduiding van een onroerende\
        \ zaak, die door het kadaster wordt vastgesteld. Percelen worden kadastraal\
        \ aangeduid door vermelding van achtereenvolgens de kadastrale gemeente en\
        \ sectie, waarin de percelen en gedeelten van percelen zijn gelegen waarvan\
        \ het grondgebied tot die zaak behoort, alsmede de nummers van die percelen.\
        \ Voor een onroerende zaak die zich krachtens een opstalrecht op, in of boven\
        \ de grond van een ander bevindt, geldt dezelfde kadastrale aanduiding als\
        \ van de onroerende zaak die met dat opstalrecht is bezwaard. Dit is van overeenkomstige\
        \ toepassing op een onroerende zaak die zich op, in of boven de grond van\
        \ een ander bevindt krachtens een recht als bedoeld in het voor 1 januari\
        \ 1992 geldende artikel 5, derde lid, onder b, laatste zinsnede, van de Belemmeringenwet\
        \ Privaatrecht. Appartementsrechten worden kadastraal aangeduid door de vermelding\
        \ van achtereenvolgens de kadastrale gemeente en sectie, waarin de in de splitsing\
        \ betrokken percelen zijn gelegen, de complexaanduiding en de appartementsindex\
        \ (Een oplopend volgnummer van `0001` tot `9999`). De complexaanduiding bestaat\
        \ uit het voor de in de splitsing betrokken percelen vastgestelde complexnummer,\
        \ gevolgd door de hoofdletter A. Onze Minister stelt regelen vast omtrent\
        \ de vaststelling van het complexnummer. Er zijn 1111 kadastrale gemeentenamen.\
        \ Elke kadastrale gemeentenaam is uniek."
      required:
      - "kadastralegemeente"
      - "sectie"
      - "perceelnummer"
      properties:
        kadastralegemeente:
          type: "string"
          title: "kadastraleGemeente"
          description: "De kadastrale gemeente, deel van de kadastrale aanduiding\
            \ van de onroerende zaak. De waarden komen uit een Waardelijst. Er zijn\
            \ 1111 kadastrale gemeentenamen. Elke kadastrale gemeentenaam is uniek."
          minLength: 1
          example: "0120"
        sectie:
          type: "string"
          title: "sectie"
          description: "Sectie is een onderverdeling van de kadastrale gemeente, bedoeld\
            \ om het werk van de meetdienst en de kadastrale kaarten overzichtelijk\
            \ te houden. Per kadastrale gemeente zijn er max. 26x26 secties . Elke\
            \ sectie heeft een of twee letters (bijv. `A`, 'B', ....'AA', 'AB', ....'ZZ'\
            \ . Alleen de sectieletter `J` werd niet gebruikt om verwarring (handgeschreven)\
            \ te voorkomen met `I`"
          minLength: 1
        perceelnummer:
          type: "integer"
          title: "perceelnummer"
          description: "Het perceelnummer dat een geheel perceel of een complex uniek\
            \ identificeert binnen de sectie. Per kadastrale gemeente en per sectie\
            \ heeft een perceel een perceelnummer oplopend door de jaren heen van\
            \ `00001` tot max `99999`"
        appartementsrechtvolgnummer:
          type: "integer"
          title: "appartementsrechtVolgnummer"
          description: "Nummer dat het kadastraal object uniek identificeert als een\
            \ appartementsrecht binnen het complex."
    Bedrag:
      type: "object"
      description: "Bedrag is samengesteld datatype voor het vastleggen van een hoeveelheid\
        \ geld in cijfers in een bepaalde valuta."
      required:
      - "som"
      - "valuta"
      properties:
        som:
          type: "integer"
          title: "som"
          description: ""
          maximum: 1.0E18
        valuta:
          type: "string"
          title: "valuta"
          description: "Aanduiding van de valutasoort."
          minLength: 1
    Waardelijst_tabel:
      type: "object"
      description: "Waardelijst is een samengesteld datatype voor het weergeven van\
        \ een gegeven binnen een extern beheerde referentielijst."
      required:
      - "code"
      properties:
        code:
          type: "string"
          title: "code"
          description: "De code van deze waarde. De code is uniek binnen de Waardelijst\
            \ en taalonafhankelijk."
          minLength: 1
        waarde:
          type: "string"
          title: "waarde"
          description: "De waarde zoals aangetroffen in de Waardelijst. het moment\
            \ waarop de waarde geassocieerd is met de meegeleverde code is onbepaald."
    Kadastraalonroerendezaak_links:
      type: "object"
      properties:
        self:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/HalLink"
        zakelijkerechten:
          title: "wordtberustdoor"
          type: "array"
          description: ""
          minItems: 1
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/HalLink"
    Zakelijkrecht_links:
      type: "object"
      properties:
        self:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/HalLink"
        zakelijkerechten:
          title: "isbelastmet"
          type: "array"
          description: ""
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/HalLink"
    Kadastraalonroerendezaak_embedded:
      type: "object"
      properties:
        zakelijkerechten:
          title: "rustOp"
          type: "array"
          description: ""
          minItems: 1
          items:
            $ref: "#/components/schemas/Zakelijkrecht"
